# .github/workflows/metrics.yml
name: Metrics

on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # Run workflow manually
  workflow_dispatch:
  # Run workflow when pushing on main/master
  push: {branches: ["main", "master"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The `contents: write` permission is required
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: JordanBuckleyGit # Replace with your GitHub username
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Dublin # Set your timezone
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_details: bytes-size, percentage
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_habits: yes
          plugin_habits_from: 200 # Days to analyze activity
          plugin_habits_days: 7 # Days to analyze within the duration
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          plugin_followup: yes
          plugin_wakatime: yes # If you use WakaTime for coding activity
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }} # Only if plugin_wakatime: yes
          plugin_wakatime_sections: time, languages, editors, os
          plugin_wakatime_limit: 5
          plugin_wakatime_days: 7
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: JordanBuckleyGit # Your WakaTime username
          plugin_wakatime_display_only: languages, editors, os
